[package]
name = "biodivine-lib-param-bn"
version = "0.1.0-beta.1"
authors = ["Samuel Pastva <daemontus@gmail.com>"]
edition = "2018"
description = "Library for working with parametrized Boolean networks."
homepage = "https://github.com/sybila/biodivine-lib-param-bn"
repository = "https://github.com/sybila/biodivine-lib-param-bn"
readme = "README.md"
keywords = ["boolean network", "asynchronous", "symbolic graph", "systems biology"]
categories = ["science", "simulation"]
license = "MIT"

[badges]
travis-ci = { repository = "sybila/biodivine-lib-param-bn" }
codecov = { repository = "sybila/biodivine-lib-param-bn" }
maintenance = { status = "actively-developed" }

[lib]
name = "biodivine_lib_param_bn"
path = "src/lib.rs"

[[bin]]
name = "dump-graph"
path = "src/bin/dump_graph.rs"

# Enable rich docs for some online docs autogen services.
[package.metadata.docs.rs]
rustdoc-args = ["--html-in-header", "docs-head.html"]

[dependencies]
regex = "1.3.3"     # used when parsing text format
biodivine-lib-bdd = "0.2.1"
roxmltree = "0.14.0"
bitvector = "0.1.5"

[features]
# With shields_up you enable explicit assertions of pre/post conditions and invariants in critical
# codepaths that cannot be proved safe by the rust compiler. Every such assertion should be proven
# correct by an associated comment. We use shields_up instead of debug_assertion to have it separated
# from debug mode (shields_up is not strictly for debugging, its a general safety net / troubleshooting
# measure). For official releases and benchmarks, you should disable shields_up to avoid unnecessary
# performance penalty. Avoid introducing dead code when shields_up is enabled - this will mess with test coverage.
shields_up = []

default = ["shields_up"]

[dev-dependencies]
pretty_assertions = "0.6.1"